sdk/__init__.py, sdk/_version.py, sdk/batch.py, sdk/client.py, sdk/job.py
Results are no longer exposed in the API when fetching a job list to save bandwidth. They need to be retrieved by querying each job successively. 
I added an option to fetch the results in the _get_jobs method. By default when a user waits for the results after declaring a batch as complete, fetch the job results.
=> Fix/ Add option to fetch job results in get_jobs

README.md, sdk/__init__.py, sdk/_version.py, sdk/batch.py, sdk/utils/enum.py
Pasqal Cloud Services do not expect anymore the device type to create a batch. It is now extracted automatically from the serialized pulser sequence. An optional emulator flag gives the ability to the user to select to run the batch on an emulator instead of a real QPU.
- Feat/ Replace explicit device_type for batch creation by optional emulator flag
- Doc/ Update basic usage in Readme
=> Feat/ Replace explicit device_type for batch creation by optional emulator flag

sdk/_version.py, sdk/batch.py
Following the change of `pending_jobs_count` to `jobs_count_per_status` on `public-apis`, this updates the SDK batch definition.
=> Update batch arguments

sdk/batch.py
Specifying an empty dict as default does not work for dataclasses.
=> Fix: Default dict specification

sdk/__init__.py, sdk/_version.py, sdk/client.py, sdk/job.py, tests/fixtures/api/batches/_.POST.json, tests/test_batch.py
This MR updates the SDK for Iroise (following the `public-apis` [update](http://gitlab.local:30080/pcs/public-apis/-/merge_requests/109)) by:
- adding a required `jobs` argument to the `create_batch` function
- adding an optional `wait` argument to that same function in case the user wants to wait for the batch results
- updating/adding tests for new functionalities
- skipping tests for temporarily disabled functionalities (`add_job` and `complete_batch` which won't be usable since the batch will automatically be completed).
=> Feat / update sdk for iroise

sdk/_version.py, sdk/batch.py, sdk/job.py
This puts the `device_status` as a batch and not job attribute.
See failing e2e test: http://gitlab.local:30080/pcs/cloud-e2e-tests/-/pipelines/5501
=> Fix  / Device status for batch

README.md, sdk/_version.py, sdk/client.py, sdk/job.py, tests/fixtures/api/jobs/22010/_.GET.json, tests/fixtures/api/jobs/_.GET.json, tests/test_batch.py
Job results are now sent in a dictionnary instead of in a string. Update the job class accordingly.
A new API endpoint has been defined to retrieve all job results for a given batch. Use that endpoint to retrieve job results when asked by the user instead of making a request for each job separately
=> Feat/ Retrieve job results as dict instead of string

sdk/__init__.py, sdk/_version.py, sdk/batch.py, sdk/client.py
The `get_batch` function with `load_results=True` was not working properly due to the attribute `jobs` of the `batch` object being assigned sometimes a list and sometimes a dict.
This fixes it, and also rationalizes the client functions so that there is only one way to get the batch results at once.
The end-to-end tests will be modified to include the use case that triggered this error.
=> Fix / Get batch function

sdk/_version.py
Previous release failed because the version was not properly bumped after rebase.
=> [PACK] Bump version

sdk/_version.py, sdk/client.py
JSON keys are necessarily string, yet the jobs are indexed with their id as an integer, thus `results.get(job_data["id"])` was always returning None. This fixes it by casting the id to `str` when parsing the response of the request.
=> [FIX] Save jobs result properly in batch object

sdk/_version.py, sdk/errors.py
`obj.get("data", {})` returns `None` if the `data` field is explicitly set to None. the default value of `get` is used only if the key is not found in the object.
500 errors seem to return a payload with a null data, thus failing the parsing.
=> Fix: HTTP errors with data = None

sdk/_version.py, sdk/batch.py
The SDK isn't capable of performing anything that would ever create/update these two values, they would simply exist in the payload when the item exists in the DB.
=> [FIX] datetime fields for batch

sdk/_version.py, sdk/client.py, sdk/job.py
Adds `start_` and `end_timestamp` fields onto job objects in the SDK in order to allow them to be deserialised from the response from the API.
- Fixes the type annotation on `_get_batch` as this was interfering with testing
=> [FEAT] Add start and end timestamps to jobs

CHANGELOG.md, sdk/endpoints.py
This changes the core endpoint to use core fast as default.
This is blocked until we release core fast to production.
However, we should already  release core fast to preprod and start telling our users to switch to core fast. I'll add it to the changelog.
=> [FEAT] Use core fast by default in the SDK

CHANGELOG.md, sdk/__init__.py, sdk/_version.py, sdk/client.py, sdk/errors.py, setup.py, tests/conftest.py, tests/fixtures/api/auth/login/_.POST.json
This feature is needed for the Jupyter Notebook of PQD which will have the JWT token stored as an environment variable. 
Right now, it is kept as a alternative mechanism to the regular login.
In order to address the issue of token expiration, a temporary error is raised which suggests the user to perform an interactive login. Therefore, a new optional parameter is added to the SDK client, namely the `login_url` to be used.
@penguinoneshaw  let me know what you think about this implementation.
=> [FEAT] Allow user to directly use a JWT token instead of logging in with username / password

.gitignore, CHANGELOG.md, README.md, pasqal_cloud/_version.py, pasqal_cloud/authentication.py, pasqal_cloud/client.py, setup.py, tests/test_client.py, tests/test_doubles/authentication.py
- Improve the `TokenProvider` abstraction. The `HTTPBearerAuthenticator` requires a `TokenProvider` and uses its `get_token` method, hence any valid `TokenProvider` should simply implement that method and not the `_query_token` method which is specific to some implementation of the token provider.
- Introduce  `ExpiringTokenProvider` abstract class in lieu of the old `TokenProvider` class
- Fix the token_provider check in the Client class. The previous implementation was bugged.
- Improve documentation formatting and fix the `CustomTokenProvider` authentication method example
=> [FIX] Custom token provider documentation

CHANGELOG.md, README.md, pasqal_cloud/__init__.py, pasqal_cloud/_version.py, pasqal_cloud/client.py, pasqal_cloud/workload.py, tests/conftest.py, tests/fixtures/api/workloads/00000000-0000-0000-0000-000000000001/_.GET.json, tests/fixtures/api/workloads/00000000-0000-0000-0000-000000000001/cancel/_.PUT.json, tests/fixtures/api/workloads/_.POST.json, tests/test_workload.py
This MR enables to use workloads through the SDK by using the create_workload, get_workload and cancel_workload methods which are hitting the corresponding endpoints in Core API. Unit tests and necessary fixtures were also added for that.
=> [FEAT] Workload support

CHANGELOG.md, pasqal_cloud/_version.py, pasqal_cloud/batch.py, tests/test_batch.py
This MR is following changes in the APIs, from now the jobs of a Batch are returned in order of insertion in the DB.
What does this MR:
- Introduce a new Batch Attribute called 'ordered_jobs which is a list of Jobs, it is basically filled with jobs data returned by the APIs without any additional transformation
- Make Batch 'jobs' attribute deprecated
- Update current tests
- Skipped Iroise tests are now operational
=> [FEAT] Batch's jobs are now returned in the same order they were created

README.md
This MR fixes the readme by removing useless imports and now indicate to use .ordered-jobs which is a list of the jobs instead of .jobs which is a dict of jobs and that is now deprecated.
=> [DOC] Update of Readme 

CHANGELOG.md, pasqal_cloud/_version.py, pasqal_cloud/errors.py, pasqal_cloud/workload.py, tests/test_workload.py
- Added `always=True` to results validator
- Added try catch for ConnectionError
- Added test for workload without result defined
- Upgraded version
=> [FIX] Add always=True to result validator

CHANGELOG.md, pasqal_cloud/__init__.py, pasqal_cloud/_version.py, pasqal_cloud/authentication.py, pasqal_cloud/batch.py, pasqal_cloud/job.py, pasqal_cloud/workload.py, setup.py, tests/test_batch.py, tests/test_device_specs.py, tests/test_job.py, tests/test_workload.py
This PR updates the version of Pydantic required by pasqal-cloud from V1.10 to V2.6.
Now pasqal-cloud needs Pydantic >= 2.6.0 to run.
=> [DEP] Bump Pydantic to V2.6

CHANGELOG.md, pasqal_cloud/__init__.py, pasqal_cloud/_version.py, pasqal_cloud/batch.py, pasqal_cloud/client.py, pasqal_cloud/errors.py, tests/conftest.py, tests/fixtures/test_payloads.py, tests/test_batch.py, tests/test_client.py, tests/test_device_specs.py, tests/test_errors.py, tests/test_workload.py
When a HTTP request fails, we will now retry it 5 times (arbitrary value, non-configurable currently) where the time between each request grows until we stop.
I've also tried to include for missing typehints and docstrings where I was updating code.
=> [IMPROVEMENT] Add exponential backoff retries to HTTP client

.github/workflows/run-tests-and-mypy-and-pre-commit-hooks.yml, .pre-commit-config.yaml, pasqal_cloud/__init__.py, pasqal_cloud/authentication.py, pasqal_cloud/batch.py, pasqal_cloud/client.py, pasqal_cloud/device/configuration/__init__.py, pasqal_cloud/device/configuration/base_config.py, pasqal_cloud/endpoints.py, pasqal_cloud/errors.py, pasqal_cloud/utils/strenum.py, pyproject.toml, sdk/__init__.py, sdk/device/__init__.py, sdk/device/configuration/__init__.py, sdk/utils/__init__.py, setup.cfg, setup.py, tests/conftest.py, tests/test_batch.py, tests/test_client.py, tests/test_cloud_sdk_import.py, tests/test_config.py, tests/test_device_specs.py, tests/test_workload.py
This PR implements ruff as the new formatter and linter for pasqal-cloud, introducing new rules to make the code cleaner.
All the rules I added in the pyproject.toml can be found on: https://docs.astral.sh/ruff/rules/
=> [DEP] Use ruff as a linter and formater instead of flake8, isort and black

CHANGELOG.md, pasqal_cloud/_version.py, pasqal_cloud/batch.py, tests/conftest.py, tests/fixtures/test_payloads.py
- Remove priority from batch attributes
- Refactor tests payloads to remove priority
- Leave priority in responses as it is still sent by public-apis
=> [CLEANUP] Remove priority from Batch attributes

.gitignore, CHANGELOG.md, pasqal_cloud/__init__.py, pasqal_cloud/_version.py, pasqal_cloud/batch.py, pasqal_cloud/client.py, pasqal_cloud/errors.py, pasqal_cloud/job.py, pasqal_cloud/workload.py, tests/test_batch.py
We need a method of submitting Jobs to a preexisting batch exposed on the interface that's being used by pulser-pasqal. I've also included a required method to mark a batch as complete via the SDK interface.
I've also updated some small nits that weren't quite right. We've got method prefixes for methods that are clearly exported into other files.
=> [DRAFT] Expose add_jobs to __init__ for use in client

pasqal_cloud/_version.py, pasqal_cloud/client.py, pasqal_cloud/utils/retry.py, tests/test_client.py
- Add a retry decorator
- Use the decorator to enable retry when downloading job results
- Refactor _request to use the new decorator
=> [IMPROVEMENT] Add a retry mechanism when downloading job results

CHANGELOG.md, README.md, pasqal_cloud/__init__.py, pasqal_cloud/_version.py, pasqal_cloud/client.py, pasqal_cloud/utils/constants.py, pasqal_cloud/utils/models.py, pyproject.toml, tests/fixtures/api/v2/jobs/_.GET.json, tests/test_batch.py, tests/test_job.py, tests/utils.py
This PR introduces a new method, get_jobs, for retrieving a list of jobs from the Pasqal backend using the V2 endpoint. The method utilizes 2 Pydantic class:
- JobFilters, allowing users to filter jobs without managing pagination manually
- PaginationParams, allowing users to manipulate pagination details such as the offset and the limit of jobs per page.
Additionally, similar enhancements have been applied to the rebatch method, incorporating the RebatchFilters class for filtering. This change is backward-incompatible.
Tests have been updated to match the new logic.
- Retrieves a list of jobs from the Pasqal backend.
- Filters jobs using the JobFilters and PaginationParams Pydantic classes.
- Does not return results from jobs.
Users can filter jobs based on several fields:
- id
- …
=> [FEAT] Get list of jobs

pasqal_cloud/_version.py, pasqal_cloud/client.py, pasqal_cloud/utils/retry.py, tests/test_client.py
Our internal e2e tests are failing due to random network issues with S3. Therefore, we have decided to extend the retry mechanism to handle exceptions, rather than relying only on HTTP status codes
=> [IMPROV] Extend the retry mechanism to handle runtime exceptions

CHANGELOG.md, pasqal_cloud/_version.py, pasqal_cloud/client.py, tests/test_client.py
- User-Agent header in headers of all authenticated requests
=> [FEAT] Headers - add user-agent

.github/workflows/publish-to-testpypi-and-pypi.yml, .github/workflows/test_release_notes.yml, .github/workflows/verify-if-secrets-were-leaked.yml, CHANGELOG.md
- Changed publish-to-testpypi-and-pypi to create a GitHub release and push to pypi when merging to main
- Added a test action to ensure release notes are formatted properly
=> [FEAT] Update release flow to create release and publish on merge with main

.github/workflows/publish-to-testpypi-and-pypi.yml
- Use v5 of setup-python in build and publish stage
=> [CI] upgrade version of setup python

.github/workflows/publish-doc-to-gh-pages.yml
This adds a GitHub Action to automatically update the MkDocs-based documentation site when the repo is updated:
This uses [this recipe](https://squidfunk.github.io/mkdocs-material/publishing-your-site/#with-github-actions) with the following changes:
- restrict the trigger condition to pushes on the `main` branch (we don't use `master`) 
- replace `pip install mkdocs-material` by `pip install .[docs]` to install all doc dependencies listed in `setup.py`
- change the action name and the cache key prefix for something more explicit 
It uses of the [built-in `mkdocs gh-pages` command](https://www.mkdocs.org/user-guide/deploying-your-docs/#project-pages) that builds and push by default to `gh-pages` from another branch with doc sources.
Tested locally with [act](https://nektosact.com/), …
=> [CI] Add GitHub action for auto-publishing docs

pasqal-cloud/pasqal_cloud/__init__.py, pasqal-cloud/pasqal_cloud/batch.py, tests/fixtures/api/v1/batches/00000000-0000-0000-0000-000000000001/jobs/_.POST.json, tests/fixtures/api/v1/batches/00000000-0000-0000-0000-000000000002/jobs/_.POST.json, tests/fixtures/api/v1/batches/_.POST.json, tests/fixtures/api/v2/batches/00000000-0000-0000-0000-000000000001/jobs/_.POST.json, tests/fixtures/api/v2/batches/00000000-0000-0000-0000-000000000002/jobs/_.POST.json
Add argument to enable backend_configurations in the SDK. These are serialised config objects from Pulser/Corresponding emulation library.
An example will be released in our docs alongside this request.
=> [FEAT] Add support for backend_configurations

tests/test_pulser_pasqal.py
`Backend.validate_sequence()` now checks that the sequence is not empty, so I'm including that in `test_pulser_pasqal.py`.
=> [FIX] Update pulser-pasqal test to account for new backend check in pulser 1.5.2

pasqal-cloud/pyproject.toml
e2e tests installation for the dev branch is broken because of this newly introduced section in the pyproject.toml. This MR removes it
=> [FIX] Get rid of unsupported dependencies section in pyproject.toml

pulser-pasqal/pulser_pasqal/__init__.py
EmuFreeBackendV2 is added to the __init__ of pulser_pasqal. This enables to import it with pulser_pasqal.EmuFreeBackendV2, just like the deprecated pulser_pasqal.EmuFreeBackend. We also rely on this to build the documentation in pulser.
Import is currently failing in https://github.com/pasqal-io/Pulser/pull/925
TBD: Do we need a hotfix ? Have to check how urgent it is at the pulser level.
=> [FEAT] Enable import of EmuFreeBackendV2 from pulser_pasqal

pasqal-cloud/pasqal_cloud/__init__.py, tests/conftest.py
Bug reported by internal user which prevents submitting with a QPUBackend to a non-Fresnel QPU.
I tested in preprod using this branch and was able to submit to FC1.
=> [FIX] Remove hard-coded references to FRESNEL for multi qpu support

.gitignore, pasqal-cloud/pasqal_cloud/__init__.py, tests/test_batch.py
Added deprecation warning for EMU_TN device_type.
Added unit test.
=> [DEPRECATION] Deprecate EMU_TN
